name: CICD for Colors App

on:
  push:
    branches:
      - setup-pipeline-github-actions

permissions:
  id-token: write
  contents: read

jobs:
  ci-dev:
    uses: ./.github/workflows/ci-steps.yml
    with:
      AWS_ACCOUNT_NUMBER: '474668381992'
      ROLE_ARN: 'arn:aws:iam::474668381992:role/GithubActionsForColorsApp'
